version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: mosaiko
    ports:
      - "8004:8004"
    restart: unless-stopped
    networks:
      - nativa-net

networks:
  nativa-net:
    external: true